name: Deploy and Restart Services

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ensf-619-fe/
          git pull origin main
          sudo rm -r /var/www/html/css
          sudo rm -r /var/www/html/js
          sudo rm /var/www/html/favicon.ico
          sudo rm /var/www/html/index.html
          sudo cp -r dist/. /var/www/html/
